export const metadata = {
    title: 'Studio',
    description: "Generated by Next.js"
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html>
            <body>
                {children}
            </body>
        </html>
    )
}